spring:
  profiles.active: local-jpa
  application:
     name: quotes

security:
  basic:
    enabled: false

expiration:
  time: -1 # enable offline mode. no expiration.

---
spring:
  profiles: local-jpa

  jpa:
      show-sql: true
      database: H2

      hibernate:
        ddl-auto: create-drop
  datasource:
      platform: h2

  database:
      driverClassName: org.postgresql.Driver

server:
  port: 8086

---
spring:
  profiles: cloud
---
api:
 url:
   company: http://dev.markitondemand.com/MODApis/Api/v2/Lookup/json?input={name}
   quote: http://dev.markitondemand.com/MODApis/Api/v2/Quote/json?symbol={symbol}